[tool.poetry]
name = "codando-deep-learning-jax"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]

[tool.poetry.dependencies]
python = "3.7.5"
jax = "^0.2.9"
jaxlib = "^0.1.60"
jupyter = "^1.0.0"
jupyterlab = "^3.0.7"
ipython = "^7.20.0"
pandas = "^1.2.2"
scikit-learn = "^0.24.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
